//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.Links = new HashSet<Link>();
            this.Stops = new HashSet<Stop>();
            this.Trains = new HashSet<Train>();
        }
    
        public int LineId { get; set; }
        public string LineName { get; set; }
        public int LineStatusId { get; set; }
    
        public virtual ICollection<Link> Links { get; set; }
        public virtual LineStatu LineStatu { get; set; }
        public virtual ICollection<Stop> Stops { get; set; }
        public virtual ICollection<Train> Trains { get; set; }
    }
}
