//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineStatu
    {
        public LineStatu()
        {
            this.Lines = new HashSet<Line>();
        }
    
        public int LineStatusId { get; set; }
        public string CurrentStatus { get; set; }
    
        public virtual ICollection<Line> Lines { get; set; }
    }
}
