//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int LinkId { get; set; }
        public string Href { get; set; }
        public string Rel { get; set; }
        public string Method { get; set; }
        public Nullable<int> LineId { get; set; }
        public Nullable<int> StopId { get; set; }
        public Nullable<int> TrainNO { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual Stop Stop { get; set; }
        public virtual Train Train { get; set; }
    }
}
