//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTEntities : DbContext
    {
        public UTEntities()
            : base("name=UTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<LineStatu> LineStatus { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<StopSchedule> StopSchedules { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<TrainStatu> TrainStatus { get; set; }
    }
}
