//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public Stop()
        {
            this.Links = new HashSet<Link>();
            this.StopSchedules = new HashSet<StopSchedule>();
        }
    
        public int StopId { get; set; }
        public int LineId { get; set; }
        public string StopName { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<StopSchedule> StopSchedules { get; set; }
    }
}
