//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopSchedule
    {
        public int TrainNO { get; set; }
        public int StopId { get; set; }
        public string ScheduledTime { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Train Train { get; set; }
    }
}
