//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanComuterTrain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainStatu
    {
        public TrainStatu()
        {
            this.Trains = new HashSet<Train>();
        }
    
        public int TrainStatusId { get; set; }
        public string CurrentStatus { get; set; }
    
        public virtual ICollection<Train> Trains { get; set; }
    }
}
